### ISSUE TITLE
navbar logo link on website broken

### ISSUE THREAD

**Issue by AdamSpannbauer** [bnosac/udpipe#12]
Not a big issue, but the link in the left of the navbar on the doc website is invalid.  It leads to https://bnosac.github.io/udpipe/ (aka 404); it should likely lead to the same location as the 'Home' link in the navbar (for me this is localized to be this link: https://bnosac.github.io/udpipe/en/index.html).

clicking this:

![image](https://user-images.githubusercontent.com/16326083/35975311-48e09f32-0caa-11e8-91fc-7db0cce5d471.png)

leads to:

![image](https://user-images.githubusercontent.com/16326083/35975326-57e7279e-0caa-11e8-8928-d849e1fc267d.png)

**Comment by jwijffels** [comment]
Yes I know, but have no clue how to fix it :)

**Comment by jwijffels** [comment]
Looks to be fixed now, by incorporating the docusaurus fix.
