### ISSUE TITLE
handle both "sent_id" and "sentence_id" for udpipe_read_conllu

### ISSUE THREAD

**Issue by HedvigS** [bnosac/udpipe#122]
Sometimes some conllu files use `sent_id` instead of the more common `sentence_id`.

Could `udpipe.:udpipe_read_conllu()` please be configured to handle both cases.

Love the package otherwise, great stuff!

**Comment by HedvigS** [comment]
For myself, I've written a little script now that checks each conllu file, if  it's got "sent_id" in it they are all replaced with "sentence_id". Hacky workaround, but will work (fingers crossed) :)

**Comment by jwijffels** [comment]
https://github.com/bnosac/udpipe/blob/master/R/udpipe_parse.R#L259 and https://github.com/bnosac/udpipe/blob/master/R/udpipe_parse.R#L265 do check for sent_id

**Comment by HedvigS** [comment]
Hm... right. When I tried reading in a few that used "sent_id" then udpipe_read_conlli" didn't work. I changed to sentence_id and then it did work. That's a bit odd then.

**Comment by HedvigS** [comment]
I'll do some more bug testing.

**Comment by jwijffels** [comment]
Can you provide a reproducible example?

**Comment by HedvigS** [comment]
> Can you provide a reproducible example?

I'm sorry to have bothered you, I just tried it again and the problem is something else. I was mistaken in thinking it was about "sent_id" vs "sentence_id". Sorry and thank you for your patience and for this wonderful package!
