### ISSUE TITLE
R: Extract Keywords from Text Vector -- one set of keyworks for each element

### ISSUE THREAD

**Issue by larry77** [bnosac/udpipe#124]
Hello,
It is not a bug, but more a cry for help :-) .
Please have a look at the question in this forum

https://stackoverflow.com/questions/78639535/r-extract-keywords-from-text-vector-one-set-of-keyworks-for-each-element

which comes with a reprex.
I am trying to get, from a text vector, not a global set of keywords, but keywords for every text element of the vector.
So far my attempts have failed and I do not know why. Is it something doable with udpipe?
Thanks a lot!

**Comment by jwijffels** [comment]
Good that you solved your own question :)
