### ISSUE TITLE
no issue, just congratulations!

### ISSUE THREAD

**Issue by randomgambit** [bnosac/udpipe#2]
amazing job, amazing package. I love the `as.data.frame` function (can you use `dplyr::data_frame` as well?). I hope the package will get better and better.  what are the next updates?

Thanks!!

**Comment by dselivanov** [comment]
no, no, no `dplyr` please. @randomgambit you can use it on your own if you really like it.

**Comment by jwijffels** [comment]
I have not plans to make this a dplyr dependency, on the contrary. I don't like the tidyverse package dependencies and was already reluctant to add the data.table dependency. 

Next on my todo list is: 
- allowing only parts of the annotation process (e.g. only tokenising, tagging or dependency parsing)
- getting the package on cran
- making models available outside cran (as they are too big in size) in other R packages for convenience
- allowing to train models based on conll-u data directly
- try to remove the data.table dependency again without speed sacrifices

**Comment by randomgambit** [comment]
@jwijffels OK OK but please consider that whether you like it or not, many users use either `dplyr` or `data.table`. Something I really like is outputting the POS tagging into a data.frame for further use. Removing the `data.table` thing would be a big mistake in my opinion.

**Comment by dselivanov** [comment]
No one prevent of the usage of favorite tools. The thing is that data.frames are base R data structures -  stable and tested. What @jwijffels have told - is that he doesn't want to have dependencies on these packages. He haven't told  that he wants to remove `as.data.frame`.
I also try to keep number of dependencies small to some extent.

**Comment by jwijffels** [comment]
@randomgambit You can just use `as.tibble` on the output of the `as.data.frame` function which is inside the `udpipe` package to get it in dplyr format if you need that for your later processing.

**Comment by randomgambit** [comment]
@dselivanov @jwijffels OK perfect then! :)
