### ISSUE TITLE
In keywords_phrases() function the is_regex=T option has broken in 0.5

### ISSUE THREAD

**Issue by sanjmeh** [bnosac/udpipe#20]
I am running side by side the same code, same data on two machines. 

One is on udpipe 0.4 and the other on udpipe 0.5 version.

The `keywords_phrases()` function is broken on 0.5 if we use `is_regex=T`

Consider the sample example in your help document.

```
data(brussels_reviews_anno, package = "udpipe")
x <- subset(brussels_reviews_anno, language %in% "fr")
np <- keywords_phrases(x$xpos, pattern = c("DT", "NN", "VB", "RB", "JJ"), sep = "-")
head(np)

```

The above should work in both 0.4 & 0.5.

Now consider the same example but with the function executed with `is_regex=T`

```
np <- keywords_phrases(x$xpos, pattern = c("DTNNVBRBJJ"), term = x$token,is_regex=T)
head(np)
# [1] keyword ngram   pattern start   end    
# <0 rows> (or 0-length row.names)
```
I tried with many regex, even as simple as just `pattern = "DTJJ"` but none works. It seems the regex option does not work.

I have also tested that regex works on the machine (an ubuntu server) by checking out the `grep ` family of commands in R. So regex does not work in the udipe function only,

**Comment by jwijffels** [comment]
Thanks for reporting. Tested this out on Windows and this did gave 72 results for
`np <- keywords_phrases(x$xpos, pattern = c("DTNNVBRBJJ"), term = x$token,is_regex=T)`
On version 0.4 as well as version 0.5. Also there has not been a change in the function when comparing version 0.4 to version 0.5 of this R package.

So this seems to be Linux specific. The regular expression uses <regex> from C++11, this was only released in version gcc 4.9.0. Which version of gcc do you have on your machine (what does `gcc --version` indicate)

**Comment by jwijffels** [comment]
Update. Checked this on Ubuntu 14.04 with gcc 4.8.4 and indeed `np <- keywords_phrases(x$xpos, pattern = c("DTNNVBRBJJ"), term = x$token,is_regex=T)` did not return anything.  While on Ubuntu 16.04 with gcc 5.4.0, everything works fine, `np <- keywords_phrases(x$xpos, pattern = c("DTNNVBRBJJ"), term = x$token,is_regex=T)` returns 72 rows.

**Comment by sanjmeh** [comment]
Hmm... Could you guess if we could fix this by some config adjustment on Ubuntu 14? As upgrading to Ubuntu 16 is a little drastic and am scared some other scripts on the server might break.

**Comment by jwijffels** [comment]
Have you re-installed the udpipe package?

**Comment by sanjmeh** [comment]
Yes indeed, I had not reinstalled udpipe.  Finally, it works. Thank you so much.  Now I can hope to load my NLP packages online on Ubuntu and share with people for annotating manually and displaying processed text using shinydashboards or fleaxdashboards. I am closing this issue now. Thanks a lot.

**Comment by jwijffels** [comment]
Feel free to share shinydashboards & flexdashboards. That would be interesting!

**Comment by sanjmeh** [comment]
@jwijffels : could you pls share your email id? Don't know how to communicate with you when there's no issue I have to report.

**Comment by jwijffels** [comment]
You can find my email here: https://github.com/bnosac/udpipe/blob/master/DESCRIPTION
