### ISSUE TITLE
Space optimization

### ISSUE THREAD

**Issue by pgrandinetti** [bnosac/udpipe#26]
Do you have recommendation on how to manage memory taken from executing `as.data.frame(udpipe_annotate(udmodel, x=documents))`? Is there anything similar to database storage, like (I think) `tm` does?

When I run that line on a collection of 10 documents, that are quite normal blog articles, the resulting data frame takes about 2.5MB in memory. Of course, I am planning to do it on many more documents and am unsure whether memory will be an issue or not.

P.S. For this small sample where the model is 2.5MB for `20748 obs. of 14 variables`, the computation takes approx 20 seconds. Seems a lot to me, but is that in line with your benchmarks?

Thanks!

**Comment by jwijffels** [comment]
Choose any DB that you like to store the annotated data. This R package does not and will not provide these. If you have 1 Mio documents with each time 200 words, that will generate 200Mio records. I tend to parallelise the annotation and then store in a database.
About speed. Please see page 10 of the paper at http://ufal.mff.cuni.cz/%7Estraka/papers/2017-conll_udpipe.pdf where you see the speed in words/second. You can easily compare that to your dataset.
If you want to parallelise things to speed up, see an example here: https://github.com/bnosac/udpipe/issues/24 or request only a part of the annotation as documented at: https://cran.r-project.org/web/packages/udpipe/vignettes/udpipe-annotation.html

**Comment by pgrandinetti** [comment]
I see, thanks.
Do you mind showing a minimal example of how do you store annotated data in your favorite DB? Or is simply the entire data.table, column by column?
The whole point would be to then have R functions that perform some optimized query, in R language. If you have to either load the entire object in the R memory every time, or to write SQL queries yourself, then it's not terribly useful (although it makes sense and I think it would still very useful to me!).
Cheers

**Comment by jwijffels** [comment]
```
library(RPostgreSQL)
dbWriteTable(mycon, name = "yourtablename", value = x)

```
