### ISSUE TITLE
Large PKG LIBS dir

### ISSUE THREAD

**Issue by dselivanov** [bnosac/udpipe#3]
You mentioned about this issue previously. Take a look to these 2 posts by Dirk, mb they will help:

1. http://dirk.eddelbuettel.com/blog/2017/08/14/#009_compact_shared_libraries
1. http://dirk.eddelbuettel.com/blog/2017/08/20/#010_stripping_shared_libraries

**Comment by jwijffels** [comment]
Thanks for the pointers. Will check this out!

**Comment by jwijffels** [comment]
Closing this, the package was accepted by CRAN and is now available at https://CRAN.R-project.org/package=udpipe
