### ISSUE TITLE
Error in udpipe_annotate: "external pointer is not valid"

### ISSUE THREAD

**Issue by eastsea17** [bnosac/udpipe#33]
**Problem description**
I try to annotate the text using R example code from the guidance below. 
(https://cran.r-project.org/web/packages/udpipe/vignettes/udpipe-annotation.html#udpipe_the_c++_library)
A week ago, the code runs very well. Any errors didn't occur. 

But, suddenly, error output appear in R console. I don't know the reason why the code stops.
I have reinstalled R and R Studio several times to delete the hidden file etc. in many directories.

Sometimes, the R studio console even stops displaying any output after executing udpipe_annotate. No error outputs are produced in R console.

Other R codes run very well. Only the UDPIPE code doesn't work.
How can I solve the problem?
(A week ago, I used R 3.3.2, I'm now using R 3.5.1)

**First Error: Error output appear in R console**

> library(udpipe)
> dl <- udpipe_download_model(language = "dutch")

Downloading udpipe model from https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.0/master/inst/udpipe-ud-2.0-170801/dutch-ud-2.0-170801.udpipe to C:/Analysis/R_Analysis/2018년/20181101_udpipe/dutch-ud-2.0-170801.udpipe
trying URL 'https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.0/master/inst/udpipe-ud-2.0-170801/dutch-ud-2.0-170801.udpipe'
Content type 'application/octet-stream' length 19992491 bytes (19.1 MB)
downloaded 19.1 MB

> str(dl)

'data.frame':	1 obs. of  3 variables:
 $ language  : chr "dutch"
 $ file_model: chr "./20181101_udpipe/dutch-ud-2.0-170801.udpipe"
 $ url       : chr "https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.0/master/inst/udpipe-ud-2.0-170801/dutch-ud-2.0-170801.udpipe"

>#Either give a file in the current working directory
> udmodel_dutch <- udpipe_load_model(file = "dutch-ud-2.0-170801.udpipe")
>#Or give the full path to the file 
> udmodel_dutch <- udpipe_load_model(file = dl$file_model)
> dl$file_model

[1] "./20181101_udpipe/dutch-ud-2.0-170801.udpipe"
> txt <- c("Ik ben de weg kwijt, kunt u me zeggen waar de Lange Wapper ligt? Jazeker meneer", 
+          "Het gaat vooruit, het gaat verbazend goed vooruit")
> x <- udpipe_annotate(udmodel_dutch, x = txt)
Error in udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger,  : 
  external pointer is not valid 
3. stop(structure(list(message = "external pointer is not valid", 
    call = udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, 
        tagger, parser, log_every, log_now), cppstack = structure(list(
        file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception",  ... 
2. udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger, 
    parser, log_every, log_now) 
1. udpipe_annotate(udmodel_dutch, x = txt) 

**Second Error: R studio console even stops displaying any output after executing udpipe_annotate**
> ud_model <- udpipe_load_model(file = "english-ud-2.0-170801.udpipe")
> x <- udpipe_annotate(ud_model, x = comments$comments)
> dd
> dd
> dd

Expected results or ordinary results are below.
> ddd
Error: object 'ddd' not found
> dd
Error: object 'dd' not found
> dd
Error: object 'dd' not found

**Comment by eastsea17** [comment]
I have already executed udpipe_load_model with right full path like an example below.

> Either give a file in the current working directory
> udmodel_dutch <- udpipe_load_model(file = "dutch-ud-2.0-170801.udpipe")
> Or give the full path to the file 
> udmodel_dutch <- udpipe_load_model(file = dl$file_model)
> udmodel_dutch <- udpipe_load_model(file = "C:/...")

I still get an error " Error in udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger,  : external pointer is not valid". 
More traceback massages are below.

> 3. stop(structure(list(message = "external pointer is not valid", 
    call = udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, 
        tagger, parser, log_every, log_now), cppstack = structure(list(
        file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception",  ... 
> 2. udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger, 
    parser, log_every, log_now) 
> 1. udpipe_annotate(ud_model, x = comments$words) 

When I click "Return with Debug", the code windows open like below

> function (udmodel, x, docid, annotation_tokenizer, annotation_tagger, 
  annotation_parser, log_every, current_time) 
> {
>   .Call("_udpipe_udp_tokenise_tag_parse", PACKAGE = "udpipe", 
    udmodel, x, docid, annotation_tokenizer, annotation_tagger, 
    annotation_parser, log_every, current_time)
> }

I tried various codes, but I couldn't have any appropriate responses like an example in official website of udpipe.

**Comment by jwijffels** [comment]
Can you copy-paste what does this give for you?

```
getwd()
list.files(full.names = TRUE)
udmodel_dutch <- udpipe_load_model(file = "dutch-ud-2.0-170801.udpipe")
udpipe::udpipe_annotate(udmodel_dutch, "Het gaat vooruit, het gaat verbazend goed vooruit")
```

**Comment by eastsea17** [comment]
It works well.
I think that my r studio have some problems. 
Sometimes, r studio console stops.
Thank you so much.

**Comment by SubhasreeUC** [comment]
I am using the English model (english-ewt-ud-2.3-181115.udpipe) to do the same thing in Studio and I can't make it work! I have tried all the options mentioned above but getting the same error: "Error in udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger,  : external pointer is not valid"

**Comment by jwijffels** [comment]
@SubhasreeUC What's your code?

**Comment by SubhasreeUC** [comment]
library(udpipe)
model <- udpipe_download_model(language = "english")
udmodel_english <- udpipe_load_model(file = '/Users/chattes4/Documents/english-ewt-ud-2.3-181115.udpipe')
txt <- as.character(data$feedback)
s <- udpipe::udpipe_annotate(udmodel_english, txt)

**Comment by jwijffels** [comment]
How big is your english-ewt-ud-2.3-181115.udpipe file in megabytes? It should be 16.7 MB.

ibrary(udpipe)
model <- udpipe_download_model(language = "english")
udmodel_english <- udpipe_load_model(file = model$file_model)
txt <- as.character(data$feedback)
s <- udpipe::udpipe_annotate(udmodel_english, txt)

**Comment by SubhasreeUC** [comment]
It is 15mb

**Comment by jwijffels** [comment]
It should be 16.7 MB

**Comment by SubhasreeUC** [comment]
While downloading in R it shows it has downloaded 16.7 MB. But when I check in application it shows 15 MB. Is that the problem?

**Comment by jwijffels** [comment]
What do you think?

**Comment by SubhasreeUC** [comment]
Thanks! That helped! Now in application the file size is 17.5mb, but the functions worked.
