### ISSUE TITLE
cooccurrence method error

### ISSUE THREAD

**Issue by fahadshery** [bnosac/udpipe#34]
Hi,

I am trying to find co-occurrence of Nouns and Adjectives. 
Below line executes fine:

`cooc <- cooccurrence(x = subset(verbatim_tokens, upos %in% c("NOUN", "ADJ")), 
                     term = "lemma", 
                     group = c("doc_id", "paragraph_id", "sentence_id"))`

When and type `cooc` in the console, it prints out fine and `View(cooc)` also works fine. But when I do `head(cooc)` within `Rmd` document it prints this weird error: `Error in `[.data.table`(data, is_list) : 
  i is not found in calling scope and it is not a column of type logical. When the first argument inside DT[...] is a single symbol, data.table looks for it in calling scope.`

**Comment by jwijffels** [comment]
Can you provide a reproducible example?

**Comment by jwijffels** [comment]
Closing. Seems not to be an issue of udpipe but of your markdown report itself. Feel free to reopen if this is udpipe-specific.
