### ISSUE TITLE
udpipe_train only works for files_conllu_training in R system directory

### ISSUE THREAD

**Issue by daboe01** [bnosac/udpipe#4]
i was constantly getting something like "too few data for gru_parser" when trying to train from my home-directory.

copying over the conllu file to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/udpipe/dummydata
fixed this.

**Comment by jwijffels** [comment]
Can you provide reproducible code for this. This looks more like you did not provide the full path to the conll-u file.

**Comment by daboe01** [comment]
you are correct. i used  the tilde as a shortcut to my home directory.
using the absolute path fixed this.

**Comment by dselivanov** [comment]
I guess we need to check that `path.expand` is used internally before passing paths to c++ code.
