### ISSUE TITLE
xpos meaning in different languages

### ISSUE THREAD

**Issue by athammad** [bnosac/udpipe#46]
Hi, 

I would like to know where I can find the correspondent meaning of each acrimonious in the filed `xpos`  when using different languages. At the current stage I am working on italian text. 

thank you

**Comment by rdatasculptor** [comment]
Maybe issue #31 will help you?

**Comment by jwijffels** [comment]
@athammad which Italian model are you using? _italian-isdt, italian-partut _or_ italian-postwita_

**Comment by athammad** [comment]
@jwijffels I am using the default treebank for italian, _italian-isdt_.

**Comment by jwijffels** [comment]
That treebank is described at https://github.com/UniversalDependencies/UD_Italian-ISDT
For the xpos tagset, look at how the authors of that treebank have defined these there.
For details on the tagset that they use in that treebank: make an issue at that repository.
