### ISSUE TITLE
Error when using sep = "_" in function keywords_collocation

### ISSUE THREAD

**Issue by love-borjeson** [bnosac/udpipe#56]
Setting the argument sep to e.g. underscore ("_") when using keywords_collocation, creates weird results downstream when using the function txt_recode_ngram: only a fraction of the mwe:s are stored in the term column. Not a biggie, " " can easily be replaced with "_" in the dtf using e.g. gsub. The hard part was to isolate the culprit, which seems to be the argument sep. Where the actual error is I don't know, but I would guess it is in the function txt_recode_ngram.

**Comment by jwijffels** [comment]
Thanks for the feedback. Can you provide a reproducible example of the weird behaviour you are encountering?

**Comment by love-borjeson** [comment]
First of all: udpipe is awesome!

Here's the code:
library(udpipe)
ud_model <- udpipe_download_model(language = "french")
data(brussels_reviews)
comments <- subset(brussels_reviews, language %in% "fr")

ud_model <- udpipe_load_model(ud_model$file_model)
x <- udpipe_annotate(ud_model, x = comments$feedback, doc_id = comments$id)
x <- as.data.frame(x)

x$topic_level_id <- unique_identifier(x, fields = c("doc_id", "paragraph_id", "sentence_id"))
#Collocations...

x_n_a <- subset(x, upos %in% c("NOUN", "ADJ"))

colloc <- keywords_collocation(x_n_a, term = "lemma", group = c("sentence_id"),
                               ngram_max = 2, n_min = 10, sep = "_")

## Recode terms to keywords
x_n_a$term <- x_n_a$lemma
x_n_a$term <- txt_recode_ngram(x_n_a$term, 
                               compound = colloc$keyword, ngram = colloc$ngram)

## Keep keyword or just plain nouns and adj
x_n_a$term <- ifelse(x_n_a$upos %in% c("NOUN", "ADJ"), x_n_a$term,
                     ifelse(x_n_a$term %in% c(colloc$keyword), x_n_a$term, NA))

## Build document/term/matrix
dtf <- document_term_frequencies(x_n_a, document = "doc_id", term = "term") #model on docs.
which(dtf == "salle", arr.ind=TRUE)
which(dtf == "salle_bain", arr.ind=TRUE)

colloc <- keywords_collocation(x_n_a, term = "lemma", group = c("sentence_id"),
                               ngram_max = 2, n_min = 10) #Here, skip the argument 'sep' to see the difference.

## Recode terms to keywords
x_n_a$term <- x_n_a$lemma
x_n_a$term <- txt_recode_ngram(x_n_a$term, 
                               compound = colloc$keyword, ngram = colloc$ngram)

## Keep keyword or just plain nouns and adj
x_n_a$term <- ifelse(x_n_a$upos %in% c("NOUN", "ADJ"), x_n_a$term,
                     ifelse(x_n_a$term %in% c(colloc$keyword), x_n_a$term, NA))

## Build document/term/matrix
dtf <- document_term_frequencies(x_n_a, document = "doc_id", term = "term") #model on docs.
which(dtf == "salle", arr.ind=TRUE)
which(dtf == "salle bain", arr.ind=TRUE)

**Comment by jwijffels** [comment]
Thanks for the report, I will look in to it next week

**Comment by jwijffels** [comment]
If you use `keywords_collocation `with argument `sep="-"`, you also need to use `txt_recode_ngram `with argument `sep = "-"`
So your code should be

```
colloc <- keywords_collocation(x_n_a, term = "lemma", group = c("sentence_id"), ngram_max = 2, n_min = 10, sep = "_")
x_n_a$term <- x_n_a$lemma
x_n_a$term <- txt_recode_ngram(x_n_a$term, compound = colloc$keyword, ngram = colloc$ngram, sep = "_")

```
