### ISSUE TITLE
How to use udpipe to replace features/tokens with lemma or POS

### ISSUE THREAD

**Issue by jansenjoost** [bnosac/udpipe#6]
Could you provide me with a lemmatization example in which you show how to replace features/tokens in my corpus of texts with lemma or POS which can be converted into a document feature matrix.

**Comment by jwijffels** [comment]
Have you looked at the documentation of ?document_term_matrix in the udpipe package. It exactly does that.

**Comment by jansenjoost** [comment]
Thanks for your answer. I’m sorry, but I cannot find that function anywhere in the documentation.

Op 19 okt. 2017, om 13:01 heeft jwijffels <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you looked at the documentation of ?document_term_matrix in the udpipe package. It exactly does that.

**Comment by jwijffels** [comment]
You need to install the latest version from github, not from cran
