### ISSUE TITLE
Unable to install udpipe on notebook azure jupyter

### ISSUE THREAD

**Issue by natand84** [bnosac/udpipe#60]
Hi,

I'm facing issues in installing udpipe package on notebook azure jupyter for using it in a text mining project.

Below the error it returns:

![Cattura](https://user-images.githubusercontent.com/53440601/62147144-36f1e700-b2f7-11e9-9dd8-8f8c30393eb1.PNG)

Can anyone help me to solve it?
thanks in advance

Andrea

**Comment by jwijffels** [comment]
Can you provide the full installation trace instead of just the warning message

**Comment by jwijffels** [comment]
Closing as no further input is provided.
