### ISSUE TITLE
parsing a file with the input format 'conllu'

### ISSUE THREAD

**Issue by FafaSame** [bnosac/udpipe#61]
I was wondering whether it is possible to parse the files which are pre-tokenized and are in conllu format? This option is possible in udpipe online service, where one can choose the input format as 'CoNLL-U'. An example is given below: 
1	In	_	_	_	_	_	_	_	_
2	the	_	_	_	_	_	_	_	_
3	end	_	_	_	_	_	_	_	_
4	,	_	_	_	_	_	_	_	_
5	we	_	_	_	_	_	_	_	_
6	should	_	_	_	_	_	_	_	_
7	acknowledge	_	_	_	_	_	_	_	_
8	that	_	_	_	_	_	_	_	_
9	currently	_	_	_	_	_	_	_	_
10	expenses	_	_	_	_	_	_	_	_
11	are	_	_	_	_	_	_	_	_
12	still	_	_	_	_	_	_	_	_
13	quite	_	_	_	_	_	_	_	_
14	high	_	_	_	_	_	_	_	_
15	.	_	_	_	_	_	_	_	_

**Comment by jwijffels** [comment]
Yes you can, you need to pass the format on to the tokenizer argument. As follows:

```
library(udpipe)
model <- udpipe_download_model("english-ewt")
model <- udpipe_load_model(model$file_model)

file <- system.file(package = "udpipe", "dummydata", "traindata.conllu")
x <- readLines(file)
#x <- readLines("yourownfile.conllu")
x <- paste(x, collapse = "\n")
cat(x)
x <- udpipe_annotate(model, x = x, tokenizer = "conllu=v2")
cat(x$conllu)
```
