### ISSUE TITLE
Documentation and behavior don't match for udpipe_download_model 

### ISSUE THREAD

**Issue by WilDoane** [bnosac/udpipe#68]
udpipe_download_model() returns a list of class "udpipe_model" while the documentation states the return value is a 1 row data.frame.

udpipe 0.8.3 CRAN

**Comment by jwijffels** [comment]
https://github.com/bnosac/udpipe/blob/be8cbfda70d63540ac87f980396231072d7465b1/R/udpipe_models.R#L363

**Comment by WilDoane** [comment]
an artifact of a dirty environment on my part, I think
