### ISSUE TITLE
Ignore underscore when annotating

### ISSUE THREAD

**Issue by alanault** [bnosac/udpipe#7]
Hi there,

Thanks for the package - it's great!

I'm using the package to annotate upos - however, I'm pre-processing where I'm replacing specific terms with tokens. They're identified with an underscore so we know they're not the word.
e.g. I love Nike > i love __brand__

However, when I run the annotation function, it processes the underscore as a symbol, rather than as a noun. Is there a way to make it ignore the underscores? I've read through the documentation, but couldn't find anything.
Many thanks
Alan

**Comment by jwijffels** [comment]
The solution to this is do your preprofessing after the annotation

**Comment by alanault** [comment]
Ah - thats a shame, my data is pre-processed, so adding features after POS tagging isn't possible.

**Comment by jwijffels** [comment]
Why don't you do the following on your annotated data set:

`x$upos <- ifelse(x$token %in% c("your", "list", "of", "brands"), "NOUN", x$upos)`

**Comment by alanault** [comment]
That's a nice (and simple) approach!

interestingly, the list of generalised tokens (like __brand__) is actually quite small, so it's not too much of an issue on a large corpus.

The token is also split into two the __brand and a "__" as well, which is labelled as punctuation. Probably worth clearing these out at the same time.

Thanks for your help and time!
