### ISSUE TITLE
Installation failing on Raspberry pi

### ISSUE THREAD

**Issue by Shyamniper** [bnosac/udpipe#71]
Installation is failing with following error:
Error: package or namespace load failed for ‘udpipe’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pi/R/arm-unknown-linux-gnueabihf-library/3.5/udpipe/libs/udpipe.so':
  /home/pi/R/arm-unknown-linux-gnueabihf-library/3.5/udpipe/libs/udpipe.so: undefined symbol: __atomic_compare_exchange_8
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/pi/R/arm-unknown-linux-gnueabihf-library/3.5/udpipe’

**Comment by jwijffels** [comment]
I have no experience with that operating system. Cran or rhub also does not have it. You will probably have more help by asking ln raspberry pi sites for
undefined symbol: __atomic_compare_exchange_8
Related to c++ compilation of c++11 code

**Comment by Shyamniper** [comment]
Modifying the Makevars file with PKG_LIBS = -pthread -latomic  yielded successful installation
may be [this](https://github.com/r-lib/later/blob/master/configure) can help other users.

Many thanks for developing this wonderful package

**Comment by jwijffels** [comment]
Interesting! Thanks for the link to the configure script. 
I would also be interested to know what you plan to use udpipe for on that Raspberry Pi device given that it only has limited amount of RAM. Any particular use case you had in mind?

**Comment by Shyamniper** [comment]
I am just learning thing right now , I am working with pi cluster surprisingly cluster of those tiny 4GB pi's allow me to do many things!

**Comment by jwijffels** [comment]
Go for it!
