### ISSUE TITLE
Parallel Processing

### ISSUE THREAD

**Issue by snvv** [bnosac/udpipe#74]
Hello
udpipe utilizes multithreaded CPU’s but udpipe_annotate and txt_sentiment uses only a single core. Is it possible to run all functions using parallel processing? 
Thank you
Sotiris

**Comment by jwijffels** [comment]
Sure that is possible. You can  use a similar setup as shown in the section on future.apply at the pkg vugnette https://cran.r-project.org/web/packages/udpipe/vignettes/udpipe-parallel.html
Just write your own FUN and use inside that function whichever calls you like to use.
