### ISSUE TITLE
Add sentiments tags

### ISSUE THREAD

**Issue by laresbernardo** [bnosac/udpipe#8]
Hello guys. 
Really enjoyed udpipe for R (and taskscheduleR as well). Have been playing with udpipe's tools for like 3 hours now on spanish texts. But I've got a request (if I may): is it possible to add if each word is positive, negative or neutral, or its positive score [-1,1], or which of the 6 sentiments adjusts more? That way we could really do a much more extensive study of our texts! 
Glad guys like you exists.
Cheers.

**Comment by jwijffels** [comment]
Hello @laresbernardo . Thanks for the positive words.
Sentiment analysis is however not within scope of udpipe. There are already so many resources which can provide you this score, it makes no sense to add another sentiment analysis package.
